**Автор: Анна Смелова**

## Решение домашнего задания к уроку 1 “Случайные события. Условная вероятность. Формула Байеса. Независимые испытания”

In [1]:
from math import factorial

In [2]:
def combinations(n, k):
    return int(factorial(n) / (factorial(k) * factorial(n - k)))

### 1. Задача
#### Из колоды в 52 карты извлекаются случайным образом 4 карты. 
#### a) Найти вероятность того, что все карты – крести. 
#### б) Найти вероятность, что среди 4-х карт окажется ХОТЯ БЫ один туз.

**<font color='darkblue'>Решение:</font>**<br>
Общее количество способов достать 4 карты из колоды в 52 карты:<br>
$C_{52}^4 = \frac{52!}{4!(52 - 4)!} = \frac{52!}{4! \cdot 48!} = \frac{52 \cdot 51 \cdot 50 \cdot 49}{1 \cdot 2 \cdot 3 \cdot 4} = 270725$

In [3]:
combinations(52, 4)

270725

**a)** 13 крестей в колоде. Вычислим количество способов извлечь 4 крести:<br>
$C_{13}^4 = \frac{13!}{4!(13 - 4)!} = \frac{52!}{4! \cdot 9!} = \frac{13 \cdot 12 \cdot 11 \cdot 10}{1 \cdot 2 \cdot 3 \cdot 4} = 715$

In [4]:
combinations(13, 4)

715

Вероятность достать 4 крести из колоды в 52 карты:<br>
$P(4clubs) = \frac{C_{13}^4}{C_{52}^4} = \frac{715}{270725} = 0.0026410564225690276$

In [5]:
715 / 270725

0.0026410564225690276

**б)** Вычислим вероятность извлечь 4 карты без тузов:<br>
$C_{52-4}^4 = c_{48}^4 = \frac{481}{4! \cdot 44!} = 194580$.

In [6]:
combinations(48, 4)

194580

Вероятность: $P(withoutace) = \frac{C_{48}^4}{C_{52}^4} = \frac{194580}{270725}$<br>
<br>
Вероятность извлечь 4 карты, среди которых есть хотя бы один туз: $P(\geq 1ace) = 1 - P(withoutace) = 1 - \frac{194580}{270725} = 0.2812632745405854$.

In [7]:
1 - 194580 / 270725

0.2812632745405854

**<font color='darkblue'>Ответ: a) вероятность того, что все карты – крести $0.0026410564225690276$;<br>б) вероятность, что среди 4-х карт окажется хотя бы один туз $0.2812632745405854$.</font>**

### 2. Задача
#### На входной двери подъезда установлен кодовый замок, содержащий десять кнопок с цифрами от 0 до 9. Код содержит три цифры, которые нужно нажать одновременно. Какова вероятность того, что человек, не знающий код, откроет дверь с первой попытки? 

**<font color='darkblue'>Решение:</font>**<br>
Всего возможных комбинаций по 3 кнопки: $C_{10}^3 = \frac{10!}{3! \cdot 7!} = \frac{10 \cdot 9 \cdot 8}{2 \cdot 3} = 120$

In [8]:
combinations(10, 3)

120

Вероятность угадать с первой попытки: $P(1try) = \frac{1}{C_{10}^3} = \frac{1}{120} = 0.008333333333333333$.

In [9]:
1 / 120

0.008333333333333333

**<font color='darkblue'>Ответ: вероятность того, что человек, не знающий код, откроет дверь с первой попытки $0.008333333333333333$.</font>**

### 3. Задача
#### В ящике имеется 15 деталей, из которых 9 окрашены. Рабочий случайным образом извлекает 3 детали. Какова вероятность того, что все извлеченные детали окрашены?

**<font color='darkblue'>Решение:</font>**<br>
Вероятность того, что первый шар окрашен: $P(first) = \frac{9}{15} = \frac{3}{5}$.<br>
Вероятность того, что второй шар окрашен: $P(second) = \frac{8}{14} = \frac{4}{7}$.<br>
Вероятность того, что третий шар окрашен: $P(third) = \frac{7}{13}$.<br>
Вероятность того, что все три окрашены: $P(all) = P(first) \cdot P(second) \cdot P(third) = \frac{3 \cdot 4 \cdot 7}{5 \cdot 7 \cdot 13} = \frac{12}{65} = 0.18461538461538463$.

In [10]:
12 / 65

0.18461538461538463

**<font color='darkblue'>Ответ: вероятность того, что все извлеченные детали окрашены $0.18461538461538463$.</font>**

### 4. Задача
#### В лотерее 100 билетов. Из них 2 выигрышных. Какова вероятность того, что 2 приобретенных билета окажутся выигрышными?

Вероятность того, что первый выигрышный: $P(1win) = \frac{2}{100}$.<br>
Вероятность того, что второй тоже выигрышный: $P(2win|1win) = \frac{1}{99}$.<br>
Вероятность того, что оба выигрышные: $P(both) = \frac{2 \cdot 1}{100 \cdot 99} = \frac{1}{99 \cdot 50} = 0.00020202020202020202$.

In [11]:
1 / (99 * 50)

0.00020202020202020202

**<font color='darkblue'>Ответ: вероятность того, что 2 приобретенных билета окажутся выигрышными $0.00020202020202020202$.</font>**